### ISSUE TITLE
Requesting PDF of this schematic

### ISSUE THREAD

**Issue by d-c-d** [adafruit/Adafruit-1.12in-128x128-OLED-PCB#1]
I would really appreciate it if the schematic was available in PDF form, thanks in advance

**Comment by tannewt** [comment]
Kicad generally opens Eagle files just fine. That way you don't need Eagle.

**Comment by ladyada** [comment]
hiya we will post the schematic as a PNG in the guide, but we dont provide PDFs. thanks :)
